---

- name: CloudEngine command test
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    cli:
      host: "XX.xx.XX.xx"
      port: "22"
      username: "xxxxx"
      password: "XXxxXXxxXXxx"
      transport: cli

  tasks:
  - name: "Run display version on remote devices"
    ce_command:
      commands: 
        - display version
      provider: "{{ cli }}"
    register: result

  - name: Debug
    debug:
      msg: "{{ result }}"

  - name: Set Variable
    set_fact:
      variable: "manufacture-info"

  - name: "Run some configuration command"
    ce_command:
      commands:
        - "display device {{ variable }}"
      provider: "{{ cli }}"
    register: result

  - name: Debug
    debug:
      msg: "{{ result }}"

  - name: Get configuration
    ce_command:
      commands:
        - "display current-configuration | include route-static 203.121.3.16"
      provider: "{{ cli }}"
    register: result

  - name: Get line 
    set_fact:
      line: "{{ result.stdout_lines[0] }}"

  - name: Get Vb
    debug:
      msg: "{{ line | last }}"
